apiVersion: v2
name: jobnik-manager
description: A Helm chart for jobnik-manager service
type: application
version: 1.0.0-rc.120
appVersion: 1.0.0-rc.120
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
